### ISSUE TITLE
Team communication

### ISSUE THREAD

**Issue by BernhardBaumrock** [BernhardBaumrock/RockTabulator#4]
Do you guys use slack? Maybe we could use it for quick chats about issues?

I'll create a PW forum thread once we have a beta available, but I don't want to do all the discussion there and I also don't want to do that in the private message @PW

Any suggestions?

**Comment by mestaritonttu** [comment]
I use IRC.

**Comment by BernhardBaumrock** [comment]
Last time I've used IRC was almost 20 years ago :D But I'm not using Slack at the moment so I wouldn't mind using IRC. What about you @mestaritonttu ?

**Comment by mestaritonttu** [comment]
I think using #processwire channel on IRC would be fine as it is silent most of the time. An example web client link: https://webchat.freenode.net/#processwire (no need to use a password). I am currently at work, so cannot join.

**Comment by jmartsch** [comment]
Many open source projects like
GravCMS
Statamic
moved to Discord because it has some advantages over Slack (disadvantages also). Our german http://webdevs.xyz/ community also [moved from Slack to Discord](https://medium.com/webdevs/webdevs-tschau-slack-hallo-discord-b0d1311a93d2) (there is also a dedicated ProcessWire channel)

There is also an english [Frontend developers Discord](https://frontenddevelopers.org/) community, but without a processwire channel.

I would recommend using Discord

**Comment by jmartsch** [comment]
I also found this Discord server https://discordapp.com/invite/q3c5thX in the PW forums: https://processwire.com/talk/topic/15594-processwire-discord-server/

Here is another one created by Soma Philipp Urlich: https://discordapp.com/invite/3jCQgt5

But there is almost no communication in each of them
